#!/usr/bin/env bash

run() {
	[ $IS_GLOBAL -eq 0 ] && $@ || sudo $@
	return $?
}

setup_symlinks() {
	local to_base="$1"
	local to_files="$(find "$to_base" -type f | sort | sed '/^$/d')"

	local install_dir
	[ "$2" != 'is_global' ] && install_dir=$HOME || install_dir=/etc
	[ "$2" = 'is_global' ] && IS_GLOBAL=1 || IS_GLOBAL=0

	while read -r to_file; do
		[ -z "$to_file" ] && continue

		local to_dir="$(dirname "$to_file" | sed "s/$to_base//")"
		local to_filename="$(basename $to_file)"

		run mkdir -p "$install_dir/$to_dir" >/dev/null 2>&1

		local from_file="$install_dir/$to_dir/$to_filename"
		echo "linking $from_file to $to_file..." >&2
		run ln -sf $PWD/$to_file $from_file || exit 1
	done <<<"$to_files"
}

main() {
	setup_symlinks user
	setup_symlinks global is_global

	sudo locale-gen
}

main
