#!/usr/bin/env sh

touchcursor_template="./setup/touchcursor-template"

get_keyboards() {
	grep -E 'Name=|Handlers=|EV=' '/proc/bus/input/devices' |
		grep -B2 EV='12001' --no-group-separator |
		grep 'Name=' |
		cut -c 4- |
		cut -d\" -f2
}

create_touchcursor_config() {
	local keyboards="$(get_keyboards)"
	local path="$HOME/.config/touchcursor"

	mkdir -p "$path"

	echo "$keyboards" | while read -r keyboard_name; do
		local escaped_name="$(echo "$keyboard_name" | sed 's/\//\\\//g')"
		local config_file="$(
			echo "$keyboard_name" |
				sed 's/ //g' |
				sed 's/\///g' |
				convconv -t kebab -a
		)"

		echo "detected keyboard: $keyboard_name" >&2

		cat "$touchcursor_template" |
			sed "s/%KEYBOARD_NAME%/$escaped_name/" \
				>"$path/${config_file}.conf"
	done
}

copy_layout() {
	sudo cp "./setup/keyboard-layout.xkb" '/usr/share/X11/xkb/symbols/custom'
}

create_touchcursor_config
copy_layout
