#!/usr/bin/env sh

touchcursor_template="./setup/touchcursor-template"

get_keyboards() {
	grep -E 'Name=|Handlers=|EV=' '/proc/bus/input/devices' |
		grep -B2 EV='12001' --no-group-separator |
		grep 'Name=' |
		cut -c 4- |
		cut -d\" -f2
}

sanitize_keyboard_name() {
	local keyboard_name="$1"

	echo "$keyboard_name" |
		sed 's/ //g' |
		sed 's/\///g' |
		convconv -t kebab -a
}

create_touchcursor_config() {
	local keyboards="$(get_keyboards)"
	local path="$HOME/.config/touchcursor"

	mkdir -p "$path"

	echo "$keyboards" | while read -r keyboard_name; do
		local escaped_name="$(echo "$keyboard_name" | sed 's/\//\\\//g')"
		local config_file="$(sanitize_keyboard_name "$keyboard_name")"

		echo "detected keyboard: $keyboard_name" >&2

		cat "$touchcursor_template" |
			sed "s/%KEYBOARD_NAME%/$escaped_name/" \
				>"$path/${config_file}.conf"
	done
}

create_systemd_files() {
	local dir="$HOME/.config/touchcursor"
	local configs="$(
		ls "$dir" |
			grep -v 'touchcursor.conf$'
	)"

	echo "$configs" | while read -r config; do
		local name="$(echo -n "$config" | sed 's/.conf$//')"

		local path="/etc/systemd/user/touchcursor-$name.service"
		sudo mkdir -p "$(dirname "$path")"

		sudo tee "$path" >/dev/null <<-EOF
			[Unit]
			Description=Touch Cursor Service - ($name)
			BindsTo=touchcursor.target

			[Service]
			ExecStart=sh -c 'ln -sf "$dir/$config" "$dir/touchcursor.conf"; /usr/bin/touchcursor;'
		EOF
	done

	local target_file=/etc/systemd/user/touchcursor.target
	sudo tee $target_file >/dev/null <<-EOF
		[Unit]
		Description=Touch Cursor Service
		BindsTo=keyboard.target
	EOF
	local reqs="$(
		echo "$configs" | while read -r config; do
			local name="touchcursor-$(echo -n "$config" | sed 's/.conf$//').service"
			echo -n "$name "
		done
	)"

	echo "Requires=$reqs" | sudo tee -a $target_file >/dev/null
}

copy_layout() {
	sudo cp "./setup/keyboard-layout.xkb" '/usr/share/X11/xkb/symbols/custom'
}

create_touchcursor_config
copy_layout
create_systemd_files
